# Generated by Django 4.2.6 on 2024-03-15 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_current_address', models.CharField(max_length=100)),
                ('employee_parmanent_address', models.CharField(max_length=100)),
                ('employee_phone_number', models.CharField(max_length=18)),
                ('employee_national_id_number', models.CharField(max_length=18)),
                ('employee_department_name', models.CharField(max_length=100)),
                ('employee_parchased_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee_return_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('deviec_sarial_number', models.IntegerField()),
                ('deviec_type', models.CharField(max_length=100)),
                ('device_description', models.TextField()),
                ('device_condition', models.CharField(default='GOOD', max_length=150)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_condition', models.TextField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='assets_app_tracker.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='assets_app_tracker.employee')),
            ],
        ),
    ]
