# Generated by Django 4.2.6 on 2024-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app_tracker', '0003_company_alter_device_company_alter_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='device',
        ),
        migrations.AddField(
            model_name='employee',
            name='device',
            field=models.ManyToManyField(to='assets_app_tracker.device'),
        ),
    ]
